"""Temporary mock data for screenshots — DO NOT COMMIT"""
from datetime import datetime, timezone, timedelta

MOCK_JOBS = [
    {"job_id": 1001, "odoo_reference": "WH/OUT/2026/0042", "sales_order_ref": "SO2026-0387",
     "customer_name": "張偉明先生", "phone": "9123 4567",
     "address": "觀塘偉業街168號 觀塘工業大廈12樓A室", "latitude": 22.3124, "longitude": 114.2254,
     "warehouse": "KH 葵興", "scheduled_date": (datetime.now(timezone.utc) + timedelta(hours=2)).isoformat(),
     "status": "assigned", "collection_required": True, "collection_method": "cash", "expected_collection_amount": 1200.0},
    {"job_id": 1002, "odoo_reference": "WH/OUT/2026/0043", "sales_order_ref": "SO2026-0391",
     "customer_name": "李美玲女士", "phone": "6845 1234",
     "address": "元朗青山公路99號 地下", "latitude": 22.4445, "longitude": 114.0228,
     "warehouse": "YL 元朗", "scheduled_date": (datetime.now(timezone.utc) + timedelta(hours=3)).isoformat(),
     "status": "accepted", "collection_required": False, "collection_method": None, "expected_collection_amount": None},
    {"job_id": 1003, "odoo_reference": "WH/OUT/2026/0038", "sales_order_ref": "SO2026-0380",
     "customer_name": "王志強醫生", "phone": "2654 3210",
     "address": "大埔廣福道55號 大埔醫療中心3樓", "latitude": 22.4493, "longitude": 114.1677,
     "warehouse": "TP 大埔", "scheduled_date": (datetime.now(timezone.utc) + timedelta(hours=1)).isoformat(),
     "status": "on_the_way", "collection_required": True, "collection_method": "fps", "expected_collection_amount": 2100.0},
    {"job_id": 1004, "odoo_reference": "WH/OUT/2026/0040", "sales_order_ref": "SO2026-0385",
     "customer_name": "陳大明先生", "phone": "2876 5432",
     "address": "葵涌葵昌路88號 葵涌廣場15樓B室", "latitude": 22.3624, "longitude": 114.1284,
     "warehouse": "KH 葵興", "scheduled_date": (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat(),
     "status": "delivered", "collection_required": True, "collection_method": "cash", "expected_collection_amount": 680.0},
    {"job_id": 1005, "odoo_reference": "WH/OUT/2026/0041", "sales_order_ref": "SO2026-0386",
     "customer_name": "黃麗芳女士", "phone": "2698 7654",
     "address": "沙田源禾路23號 沙田商業大廈6樓", "latitude": 22.3825, "longitude": 114.1886,
     "warehouse": "KH 葵興", "scheduled_date": (datetime.now(timezone.utc) - timedelta(days=1)).isoformat(),
     "status": "failed", "collection_required": False, "collection_method": None, "expected_collection_amount": None},
]
